export const ROLES = {
  PATIENT: 'PATIENT',
  CLINIC_PARTNER: 'CLINIC_PARTNER',
  CLINIC_STAFF: 'CLINIC_STAFF',
  ADMIN: 'ADMIN',
};

export const SLOT_STATUS = {
  AVAILABLE: 'AVAILABLE',
  HELD: 'HELD',
  BOOKED: 'BOOKED',
  OVER_DATE: 'OVER_DATE',
};

export const APPOINTMENT_STATUS = {
  HELD: 'HELD',
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  CONFIRMED: 'CONFIRMED',
  CHECKED_IN: 'CHECKED_IN',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
  OVER_DATE: 'OVER_DATE',
};

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
};

export const DEFAULT_DEPOSIT_AMOUNT = 100000;

